// Generated by scripts/generate-dataset-registry.ts. Do not edit.
import type { DatasetDefinition } from "./types";
import { airQualityDatasetDefinition } from "./definitions/airQuality";
import { brexitDatasetDefinition } from "./definitions/brexit";
import { brexitConstituencyDatasetDefinition } from "./definitions/brexitConstituency";
import { broadbandDatasetDefinition } from "./definitions/broadband";
import { carAvailabilityDatasetDefinition } from "./definitions/carAvailability";
import { childPovertyDatasetDefinition } from "./definitions/childPoverty";
import { claimantCountDatasetDefinition } from "./definitions/claimantCount";
import { crimeDatasetDefinition } from "./definitions/crime";
import { ethnicityDatasetDefinition } from "./definitions/ethnicity";
import { fuelPovertyDatasetDefinition } from "./definitions/fuelPoverty";
import { generalElectionDatasetDefinition } from "./definitions/generalElection";
import { ghgEmissionsDatasetDefinition } from "./definitions/ghgEmissions";
import { historicalGeneralElectionDatasetDefinition } from "./definitions/historicalGeneralElection";
import { homelessnessDatasetDefinition } from "./definitions/homelessness";
import { housePriceDatasetDefinition } from "./definitions/housePrice";
import { imdDatasetDefinition } from "./definitions/imd";
import { incomeDatasetDefinition } from "./definitions/income";
import { jobsDatasetDefinition } from "./definitions/jobs";
import { landAreaDatasetDefinition } from "./definitions/landArea";
import { lifeExpectancyDatasetDefinition } from "./definitions/lifeExpectancy";
import { lifeExpectancySeriesDatasetDefinition } from "./definitions/lifeExpectancySeries";
import { localElectionDatasetDefinition } from "./definitions/localElection";
import { mobileCoverageDatasetDefinition } from "./definitions/mobileCoverage";
import { nhsWaitingDatasetDefinition } from "./definitions/nhsWaiting";
import { nimdmDatasetDefinition } from "./definitions/nimdm";
import { populationDatasetDefinition } from "./definitions/population";
import { populationConstituencyDatasetDefinition } from "./definitions/populationConstituency";
import { populationUkDatasetDefinition } from "./definitions/populationUk";
import { qualificationDatasetDefinition } from "./definitions/qualification";
import { roadCollisionsDatasetDefinition } from "./definitions/roadCollisions";
import { schoolPerformanceDatasetDefinition } from "./definitions/schoolPerformance";
import { schoolPerformanceConstituencyDatasetDefinition } from "./definitions/schoolPerformanceConstituency";
import { schoolPerformanceDisadvantageDatasetDefinition } from "./definitions/schoolPerformanceDisadvantage";
import { simdDatasetDefinition } from "./definitions/simd";
import { travelToWorkDatasetDefinition } from "./definitions/travelToWork";
import { unemploymentDatasetDefinition } from "./definitions/unemployment";
import { wimdDatasetDefinition } from "./definitions/wimd";

/** The complete framework-neutral catalogue used by compilers and API consumers. */
export const CATALOGUE_DATASET_DEFINITIONS: readonly DatasetDefinition[] = [
	airQualityDatasetDefinition,
	brexitDatasetDefinition,
	brexitConstituencyDatasetDefinition,
	broadbandDatasetDefinition,
	carAvailabilityDatasetDefinition,
	childPovertyDatasetDefinition,
	claimantCountDatasetDefinition,
	crimeDatasetDefinition,
	ethnicityDatasetDefinition,
	fuelPovertyDatasetDefinition,
	generalElectionDatasetDefinition,
	ghgEmissionsDatasetDefinition,
	historicalGeneralElectionDatasetDefinition,
	homelessnessDatasetDefinition,
	housePriceDatasetDefinition,
	imdDatasetDefinition,
	incomeDatasetDefinition,
	jobsDatasetDefinition,
	landAreaDatasetDefinition,
	lifeExpectancyDatasetDefinition,
	lifeExpectancySeriesDatasetDefinition,
	localElectionDatasetDefinition,
	mobileCoverageDatasetDefinition,
	nhsWaitingDatasetDefinition,
	nimdmDatasetDefinition,
	populationDatasetDefinition,
	populationConstituencyDatasetDefinition,
	populationUkDatasetDefinition,
	qualificationDatasetDefinition,
	roadCollisionsDatasetDefinition,
	schoolPerformanceDatasetDefinition,
	schoolPerformanceConstituencyDatasetDefinition,
	schoolPerformanceDisadvantageDatasetDefinition,
	simdDatasetDefinition,
	travelToWorkDatasetDefinition,
	unemploymentDatasetDefinition,
	wimdDatasetDefinition,
];
