// Generated by scripts/generate-dataset-registry.ts. Do not edit.
import type { DatasetDefinition } from "./types";
import { airQualityDatasetDefinition } from "./definitions/airQuality";
import { brexitDatasetDefinition } from "./definitions/brexit";
import { brexitConstituencyDatasetDefinition } from "./definitions/brexitConstituency";
import { broadbandDatasetDefinition } from "./definitions/broadband";
import { childPovertyDatasetDefinition } from "./definitions/childPoverty";
import { claimantCountDatasetDefinition } from "./definitions/claimantCount";
import { crimeDatasetDefinition } from "./definitions/crime";
import { ethnicityDatasetDefinition } from "./definitions/ethnicity";
import { fuelPovertyDatasetDefinition } from "./definitions/fuelPoverty";
import { generalElectionDatasetDefinition } from "./definitions/generalElection";
import { historicalGeneralElectionDatasetDefinition } from "./definitions/historicalGeneralElection";
import { homelessnessDatasetDefinition } from "./definitions/homelessness";
import { housePriceDatasetDefinition } from "./definitions/housePrice";
import { imdDatasetDefinition } from "./definitions/imd";
import { incomeDatasetDefinition } from "./definitions/income";
import { lifeExpectancyDatasetDefinition } from "./definitions/lifeExpectancy";
import { localElectionDatasetDefinition } from "./definitions/localElection";
import { nhsWaitingDatasetDefinition } from "./definitions/nhsWaiting";
import { nimdmDatasetDefinition } from "./definitions/nimdm";
import { populationDatasetDefinition } from "./definitions/population";
import { populationUkDatasetDefinition } from "./definitions/populationUk";
import { qualificationDatasetDefinition } from "./definitions/qualification";
import { schoolPerformanceDatasetDefinition } from "./definitions/schoolPerformance";
import { simdDatasetDefinition } from "./definitions/simd";
import { unemploymentDatasetDefinition } from "./definitions/unemployment";
import { wimdDatasetDefinition } from "./definitions/wimd";

/** The complete framework-neutral catalogue used by compilers and API consumers. */
export const CATALOGUE_DATASET_DEFINITIONS: readonly DatasetDefinition[] = [
	airQualityDatasetDefinition,
	brexitDatasetDefinition,
	brexitConstituencyDatasetDefinition,
	broadbandDatasetDefinition,
	childPovertyDatasetDefinition,
	claimantCountDatasetDefinition,
	crimeDatasetDefinition,
	ethnicityDatasetDefinition,
	fuelPovertyDatasetDefinition,
	generalElectionDatasetDefinition,
	historicalGeneralElectionDatasetDefinition,
	homelessnessDatasetDefinition,
	housePriceDatasetDefinition,
	imdDatasetDefinition,
	incomeDatasetDefinition,
	lifeExpectancyDatasetDefinition,
	localElectionDatasetDefinition,
	nhsWaitingDatasetDefinition,
	nimdmDatasetDefinition,
	populationDatasetDefinition,
	populationUkDatasetDefinition,
	qualificationDatasetDefinition,
	schoolPerformanceDatasetDefinition,
	simdDatasetDefinition,
	unemploymentDatasetDefinition,
	wimdDatasetDefinition,
];
