// Generated by scripts/generate-dataset-registry.ts. Do not edit.
import type { DatasetDefinition } from "./types";
import { adultSocialCareActivityDatasetDefinition } from "./definitions/adultSocialCareActivity";
import { adultSocialCareOutcomesDatasetDefinition } from "./definitions/adultSocialCareOutcomes";
import { airQualityDatasetDefinition } from "./definitions/airQuality";
import { brexitDatasetDefinition } from "./definitions/brexit";
import { brexitConstituencyDatasetDefinition } from "./definitions/brexitConstituency";
import { broadbandDatasetDefinition } from "./definitions/broadband";
import { businessActivityDatasetDefinition } from "./definitions/businessActivity";
import { carAvailabilityDatasetDefinition } from "./definitions/carAvailability";
import { childPovertyDatasetDefinition } from "./definitions/childPoverty";
import { claimantCountDatasetDefinition } from "./definitions/claimantCount";
import { councilTaxDatasetDefinition } from "./definitions/councilTax";
import { crimeDatasetDefinition } from "./definitions/crime";
import { electricVehicleChargersDatasetDefinition } from "./definitions/electricVehicleChargers";
import { electricityConsumptionDatasetDefinition } from "./definitions/electricityConsumption";
import { ethnicityDatasetDefinition } from "./definitions/ethnicity";
import { fuelPovertyDatasetDefinition } from "./definitions/fuelPoverty";
import { gasConsumptionDatasetDefinition } from "./definitions/gasConsumption";
import { generalElectionDatasetDefinition } from "./definitions/generalElection";
import { ghgEmissionsDatasetDefinition } from "./definitions/ghgEmissions";
import { historicalGeneralElectionDatasetDefinition } from "./definitions/historicalGeneralElection";
import { homelessnessDatasetDefinition } from "./definitions/homelessness";
import { housePriceDatasetDefinition } from "./definitions/housePrice";
import { imdDatasetDefinition } from "./definitions/imd";
import { incomeDatasetDefinition } from "./definitions/income";
import { jobsDatasetDefinition } from "./definitions/jobs";
import { landAreaDatasetDefinition } from "./definitions/landArea";
import { lifeExpectancyDatasetDefinition } from "./definitions/lifeExpectancy";
import { lifeExpectancySeriesDatasetDefinition } from "./definitions/lifeExpectancySeries";
import { localElectionDatasetDefinition } from "./definitions/localElection";
import { localGovernmentFinanceDatasetDefinition } from "./definitions/localGovernmentFinance";
import { mobileCoverageDatasetDefinition } from "./definitions/mobileCoverage";
import { netAdditionalDwellingsDatasetDefinition } from "./definitions/netAdditionalDwellings";
import { nhsWaitingDatasetDefinition } from "./definitions/nhsWaiting";
import { nimdmDatasetDefinition } from "./definitions/nimdm";
import { planningApplicationsDatasetDefinition } from "./definitions/planningApplications";
import { populationDatasetDefinition } from "./definitions/population";
import { populationConstituencyDatasetDefinition } from "./definitions/populationConstituency";
import { populationUkDatasetDefinition } from "./definitions/populationUk";
import { qualificationDatasetDefinition } from "./definitions/qualification";
import { regionalGdpItl1DatasetDefinition } from "./definitions/regionalGdpItl1";
import { regionalGdpItl2DatasetDefinition } from "./definitions/regionalGdpItl2";
import { regionalGdpItl3DatasetDefinition } from "./definitions/regionalGdpItl3";
import { roadCollisionsDatasetDefinition } from "./definitions/roadCollisions";
import { schoolPerformanceDatasetDefinition } from "./definitions/schoolPerformance";
import { schoolPerformanceConstituencyDatasetDefinition } from "./definitions/schoolPerformanceConstituency";
import { schoolPerformanceDisadvantageDatasetDefinition } from "./definitions/schoolPerformanceDisadvantage";
import { simdDatasetDefinition } from "./definitions/simd";
import { travelToWorkDatasetDefinition } from "./definitions/travelToWork";
import { unemploymentDatasetDefinition } from "./definitions/unemployment";
import { wasteDatasetDefinition } from "./definitions/waste";
import { wimdDatasetDefinition } from "./definitions/wimd";
import { workplaceIncomeDatasetDefinition } from "./definitions/workplaceIncome";

/** The complete framework-neutral catalogue used by compilers and API consumers. */
export const CATALOGUE_DATASET_DEFINITIONS: readonly DatasetDefinition[] = [
	adultSocialCareActivityDatasetDefinition,
	adultSocialCareOutcomesDatasetDefinition,
	airQualityDatasetDefinition,
	brexitDatasetDefinition,
	brexitConstituencyDatasetDefinition,
	broadbandDatasetDefinition,
	businessActivityDatasetDefinition,
	carAvailabilityDatasetDefinition,
	childPovertyDatasetDefinition,
	claimantCountDatasetDefinition,
	councilTaxDatasetDefinition,
	crimeDatasetDefinition,
	electricVehicleChargersDatasetDefinition,
	electricityConsumptionDatasetDefinition,
	ethnicityDatasetDefinition,
	fuelPovertyDatasetDefinition,
	gasConsumptionDatasetDefinition,
	generalElectionDatasetDefinition,
	ghgEmissionsDatasetDefinition,
	historicalGeneralElectionDatasetDefinition,
	homelessnessDatasetDefinition,
	housePriceDatasetDefinition,
	imdDatasetDefinition,
	incomeDatasetDefinition,
	jobsDatasetDefinition,
	landAreaDatasetDefinition,
	lifeExpectancyDatasetDefinition,
	lifeExpectancySeriesDatasetDefinition,
	localElectionDatasetDefinition,
	localGovernmentFinanceDatasetDefinition,
	mobileCoverageDatasetDefinition,
	netAdditionalDwellingsDatasetDefinition,
	nhsWaitingDatasetDefinition,
	nimdmDatasetDefinition,
	planningApplicationsDatasetDefinition,
	populationDatasetDefinition,
	populationConstituencyDatasetDefinition,
	populationUkDatasetDefinition,
	qualificationDatasetDefinition,
	regionalGdpItl1DatasetDefinition,
	regionalGdpItl2DatasetDefinition,
	regionalGdpItl3DatasetDefinition,
	roadCollisionsDatasetDefinition,
	schoolPerformanceDatasetDefinition,
	schoolPerformanceConstituencyDatasetDefinition,
	schoolPerformanceDisadvantageDatasetDefinition,
	simdDatasetDefinition,
	travelToWorkDatasetDefinition,
	unemploymentDatasetDefinition,
	wasteDatasetDefinition,
	wimdDatasetDefinition,
	workplaceIncomeDatasetDefinition,
];
