import { envelope, type ApiResponse } from "./routeResponse";
import type { RouteRequest } from "./routing";

/** The API's entry point, linking every resource it serves. */
export const handleIndexRoutes = ({
	releaseId,
	segments,
}: RouteRequest): ApiResponse | undefined => {
	if (segments.length !== 1 || segments[0] !== "v1") return undefined;
	return {
		status: 200,
		body: envelope(releaseId, {
			name: "UK Data Atlas API",
			// The binding description of these routes, served as a document.
			openapi: "/v1/openapi.yaml",
			// The same contract for a person to read, with quick starts.
			documentation: "/v1/docs",
			links: [
				"/v1/openapi.yaml",
				"/v1/docs",
				"/v1/geographies",
				"/v1/map-resources",
				"/v1/map-resources/{geography}/{release}",
				"/v1/map-resources/{geography}/{release}.pmtiles",
				"/v1/map-resources/{geography}/{release}/tiles.json",
				"/v1/map-resources/{geography}/{release}/tiles/{z}/{x}/{y}.mvt",
				"/v1/map-resources/{geography}/{release}/features",
				"/v1/map-resources/{geography}/{release}/join/{measure-id}",
				"/v1/atlas-releases/{release-id}/map-resources/{geography}/{release}",
				"/v1/boundary-releases",
				"/v1/boundary-releases:resolve",
				"/v1/boundary-releases/{geography}/{release}",
				"/v1/geography-inventory",
				"/v1/terrain",
				"/v1/terrain/{terrain-id}",
				"/v1/terrain/elevation/point",
				"/v1/coordinates:convert",
				"/v1/datasets",
				"/v1/datasets/{dataset-id}",
				"/v1/measures",
				"/v1/measures/{measure-id}",
				"/v1/measures/{measure-id}/compatibility",
				"/v1/measures/{measure-id}/coverage",
				"/v1/measures/{measure-id}/quality",
				"/v1/measures/{measure-id}/conversion-support",
				"/v1/analysis-geographies",
				"/v1/analysis-geography-validation",
				"/v1/analysis:plan",
				"/v1/data/{measure-id}",
				"/v1/data/{measure-id}/series",
				"/v1/data/{measure-id}/rankings",
				"/v1/data/{measure-id}/change",
				"/v1/data/{measure-id}/value",
				"/v1/places",
				"/v1/data/{measure-id}/compare",
				"/v1/data/{measure-id}/aggregate",
				"/v1/data/{measure-id}/convert",
				"/v1/areas",
				"/v1/areas:resolve",
				"/v1/areas:contains",
				"/v1/areas:containsBatch",
				"/v1/areas:near",
				"/v1/areas:intersects",
				"/v1/areas:validate",
				"/v1/areas/{geography}/{release}/{code}",
				"/v1/areas/{geography}/{release}/{code}/dossier",
				"/v1/areas/{geography}/{release}/{code}/history",
				"/v1/areas/{geography}/{release}/{code}/parents",
				"/v1/areas/{geography}/{release}/{code}/children",
				"/v1/areas/{geography}/{release}/{code}/children/geometry",
				"/v1/areas/{geography}/{release}/{code}/relationships",
				"/v1/areas/{geography}/{release}/{code}/neighbours",
				"/v1/areas/{geography}/{release}/{code}/overlap",
				"/v1/areas/{geography}/{release}/{code}/capabilities",
				"/v1/areas/{geography}/{release}/{code}/citation",
				"/v1/areas/{geography}/{release}/{code}/geometry",
				"/v1/areas/{geography}/{release}/{code}/geometry/metadata",
				"/v1/translations",
				"/v1/attribution",
				"/v1/corrections",
				"/v1/locations",
				"/v1/locations/{location-id}",
				"/v1/locations/{location-id}/capabilities",
				"/v1/locations/{location-id}/members",
				"/v1/locations/{location-id}/parents",
				"/v1/relationship-paths",
				"/v1/crosswalks",
				"/v1/crosswalks/{crosswalk-id}",
				"/v1/crosswalks/{crosswalk-id}/records",
				"/v1/relationship-candidates",
				"/v1/validation",
				"/v1/validation/boundary-releases/{geography}/{release}",
				"/v1/validation/crosswalks/{crosswalk-id}",
				"/v1/validation/measures/{measure-id}",
				"/v1/validation/exports/{export-id}",
				"/v1/exports",
				"/v1/exports/{export-id}",
				"/v1/lookups",
				"/v1/lookups/{lookup-id}",
				"/v1/atlas-release",
				"/v1/atlas-releases",
				"/v1/atlas-releases/{release-id}/artifacts",
				"/v1/atlas-releases/{release-id}",
				"/v1/atlas-releases/compare",
			],
		}),
	};
};
