import { createHash } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { precompileFingerprint } from "./precompile-fingerprint.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const datasets = join(root, "public", "data", "datasets");
const manifestPath = join(datasets, "dataset-manifest.json");

type Manifest = {
	precompiler?: { fingerprint?: string };
	datasets?: Array<{
		type: string;
		output: string;
		compiled: { bytes: number; sha256: string };
	}>;
};

const fail = (message: string): never => {
	throw new Error(
		`${message} Run pnpm precompile locally and commit public/data/.`,
	);
};

const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as Manifest;
const expectedFingerprint = manifest.precompiler?.fingerprint;
if (!expectedFingerprint) fail("Precompiled data has no compiler fingerprint.");
const actualFingerprint = await precompileFingerprint(root);
if (actualFingerprint !== expectedFingerprint)
	fail("Precompiled data was generated by different compiler inputs.");

for (const dataset of manifest.datasets ?? []) {
	const path = join(datasets, `${dataset.output}.json`);
	const contents = await readFile(path);
	const digest = createHash("sha256").update(contents).digest("hex");
	if (
		contents.byteLength !== dataset.compiled.bytes ||
		digest !== dataset.compiled.sha256
	)
		fail(
			`Precompiled ${dataset.type} does not match dataset-manifest.json.`,
		);
}

await stat(join(datasets, "docs-catalogue.json"));
await stat(join(root, "public", "data", "boundaries"));
console.log(
	"Committed precompiled data matches its manifest and compiler inputs.",
);
