import { createHash } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { boundaryChunkProblems } from "./boundary-chunks";
import { precompileFingerprints } from "./precompile-fingerprint.mjs";
import { resolverProjectionProblems } from "./resolver-projections";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const datasets = join(root, "public", "data", "datasets");
const manifestPath = join(datasets, "dataset-manifest.json");

type Manifest = {
	precompiler?: { fingerprint?: string };
	datasets?: Array<{
		type: string;
		output: string;
		fingerprint?: string;
		compiled: { bytes: number; sha256: string };
	}>;
};

const fail = (message: string): never => {
	throw new Error(`${message} Run pnpm precompile locally.`);
};

const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as Manifest;
const expectedFingerprint = manifest.precompiler?.fingerprint;
if (!expectedFingerprint) fail("Precompiled data has no compiler fingerprint.");
const actual = await precompileFingerprints(root);
if (actual.pipeline !== expectedFingerprint)
	fail("Precompiled data was generated by different compiler inputs.");

const manifestTypes = (manifest.datasets ?? []).map(({ type }) => type);
const expectedTypes = Object.keys(actual.datasets);
if (
	manifestTypes.length !== expectedTypes.length ||
	expectedTypes.some((type) => !manifestTypes.includes(type))
)
	fail("Precompiled datasets are not the datasets the catalogue defines.");

for (const dataset of manifest.datasets ?? []) {
	if (dataset.fingerprint !== actual.datasets[dataset.type])
		fail(
			`Precompiled ${dataset.type} was generated by different compiler inputs.`,
		);
	const path = join(datasets, `${dataset.output}.json`);
	const contents = await readFile(path);
	const digest = createHash("sha256").update(contents).digest("hex");
	if (
		contents.byteLength !== dataset.compiled.bytes ||
		digest !== dataset.compiled.sha256
	)
		fail(
			`Precompiled ${dataset.type} does not match dataset-manifest.json.`,
		);
}

// The resolver's answers are compiled from the API build, which is not
// committed, so they are checked against their own record instead.
const projectionProblems = resolverProjectionProblems(datasets);
if (projectionProblems.length > 0)
	throw new Error(projectionProblems.join("\n"));

const chunkProblems = await boundaryChunkProblems(root);
if (chunkProblems.length > 0)
	throw new Error(
		`${chunkProblems.join("\n")}\nRun pnpm precompile locally.`,
	);

await stat(join(datasets, "docs-catalogue.json"));
await stat(join(root, "public", "data", "boundaries"));
console.log(
	"Committed precompiled data matches its manifest, compiler inputs and API build.",
);
